name: annette_app
description: Annette App 3.0

publish_to: 'none'

version: 4.0.5+15

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  week_of_year: ^2.0.0
  provider: ^6.0.0
  page_view_indicators: ^2.0.0
  quick_actions: ^0.6.0+3
  flutter_slidable: ^0.6.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12
  path_provider: ^2.0.2
  http: ^0.13.3
  yaml: ^3.1.1
  get_storage: ^2.0.3
  flutter:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1
  flutter_local_notifications: ^8.1.1+1
  sqflite: ^2.0.0+3
  path: ^1.8.0
  cupertino_icons: ^1.0.3
  google_fonts: ^3.0.1
  flutter_markdown: ^0.6.10+2
  flutter_pdfview: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/vertretungDemo.png
    - assets/images/homeworkDemo.png
    - assets/images/timetableDemo.png
    - pubspec.yaml

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
