
List<String> getSubjectsFullName() {
  List<String> classesFullName = [
    'Deutsch',
    'Mathe',
    'Englisch',
    'Musik',
    'Kunst',
    'Chemie',
    'Biologie',
    'Geschichte',
    'Erdkunde',
    'Pädagogik',
    'Spanisch',
    'Spanisch',
    'Englisch VT',
    'Mathe VT',
    'Französisch',
    'Französisch',
    'Informatik',
    'Informatik Diff.',
    'Philosophie',
    'Philosophie',
    'Kath. Religion',
    'Ev. Religion',
    'Latein',
    'Latein',
    'Französisch',
    'Sport',
    'Mittagspause',
    'Mittagspause',
    'Litertur',
    'Lernzeit',
    'Physik Diff.',
    'Geschichte Diff.',
    'Kunst Diff.',
    'Politik',
    'Englisch Förder',
    'Deutsch Förder',
    'Mathe Förder',
    'Latein Förder',
    'Orientierungsstunde',
    'Nicht angegeben',
    'Physik'
  ];

  return classesFullName;
}

List<String> getSubjectsAbbreviation() {
  List<String> classesAbbreviation = [
    'D',
    'M',
    'E',
    'MU',
    'KU',
    'CH',
    'BI',
    'GE',
    'EK',
    'PA',
    'S8',
    'S10',
    'E VT',
    'M VT',
    'F5',
    'F6',
    'IF',
    'IFd',
    'PL',
    'PPL',
    'KR',
    'ER',
    'L6',
    'L',
    'F',
    'SP',
    'MP',
    'MP MH',
    'LIT',
    'LZ',
    'PHd',
    'GEd',
    'KUd',
    'PK',
    'E FÖ',
    'D FÖ',
    'M FÖ',
    'L FÖ',
    'OS',
    '&nbsp;',
    'PH'
  ];

  return classesAbbreviation;
}


